services:
  ollama:
    image: ollama/ollama:latest
    container_name: llama_ai
    environment:
      # ESSENCIAL: Permite que o container do Juice Shop converse com o Ollama
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - juice_net

  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    environment:
      - JUICE_SHOP_CHATBOT_LLM_API_URL=http://ollama:11434/v1
      - JUICE_SHOP_CHATBOT_MODEL=llama3.2:1b
    depends_on:
      - ollama
    networks:
      - juice_net

volumes:
  ollama_data:

networks:
  juice_net:
    driver: bridge
