services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - juice_net

  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    environment:
      # URL da API apontando para o container vizinho dentro da rede do Docker
      - JUICE_SHOP_CHATBOT_LLM_API_URL=http://ollama:11434/v1
      # Modelo ultra enxuto (1.3GB de RAM), ideal para a sua VM
      - JUICE_SHOP_CHATBOT_MODEL=llama3.2:1b
    depends_on:
      - ollama
    networks:
      - juice_net

volumes:
  ollama_data:

networks:
  juice_net:
    driver: bridge
